repos:
  # Black - Python code formatter
  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3.13
        args: [--line-length=100]

  # Flake8 - Style guide enforcement
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
        args: [--max-line-length=100, --extend-ignore=E203,W503]
        additional_dependencies: [flake8-docstrings]

  # isort - Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.14.0
    hooks:
      - id: isort
        args: [--profile=black, --line-length=100]

  # mypy - Static type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
      - id: mypy
        additional_dependencies:
          - types-PyYAML
          - types-requests
          - types-pillow
        args: [--ignore-missing-imports, --no-strict-optional]

  # Standard pre-commit hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
        args: [--maxkb=1000]
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

  # Prettier - YAML, JSON, Markdown formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0
    hooks:
      - id: prettier
        types_or: [yaml, markdown, json]
        exclude: experiments/

  # Python security checks
  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.0
    hooks:
      - id: bandit
        args: [-c, pyproject.toml]
        additional_dependencies: ["bandit[toml]"]

  # Notebook cleanup
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.9.2
    hooks:
      - id: nbqa-black
      - id: nbqa-isort
      - id: nbqa-flake8
